### ISSUE TITLE
Run Time Improvement

### ISSUE THREAD

**Issue by ryan-harrington** [Dapp3rDuck/fractals#3]
Write or modify an algorithm to speed up fractal render time. (Recursion?)

**Comment by ryan-harrington** [comment]
The 2 main reasons why the fractals take so long to render:
1. iterations (1000)
2. resolution

In order to resolve that, first we need to identify an ideal number of iterations for a fractal; a recommended or default value. This goes for it's resolution as well. Inside of the fractal method, each iteration is calculated. 
```py
for i in range(1, ITERATIONS):
     if abs(z) > 2: return rgb_conv(i)
    z = eval(FRACTAL)

return (0, 0, 0)
```
If the absolute value of `z` is never greater than `2`, `z` is set equal to `eval(FRACTAL)`. 
When the fractal method is called inside of a second loop, each pixel is iterated over.
```py
for x in range(img.size[0]):
    print("%.2f %%" % (x / WIDTH * 100.0))
    for y in range(img.size[1]): pixels[x, y] = fractal(x, y)
```
Unless there is a method for skipping a number of pixels and setting it to a default RGB value of `(0, 0, 0)`, a shorthand method for looping over each iteration is necessary.

**Comment by nJohnson02** [comment]
Using PyInstaller to compile the script to binary (exe) will improve run-time efficiency.
We still need to try and find a way to analytically determine if the point will escape to infinity, or remain bounded.
