### ISSUE TITLE
Coordinates based on domain and range.

### ISSUE THREAD

**Issue by ryan-harrington** [Dapp3rDuck/fractals#5]
Output a graphic or text output after rendering of the coordinates for each corner and midpoint.

**Comment by nJohnson02** [comment]
IDEA: Use an if statement to assign white to certain pixels to form a grid above the image, then have it spit out a txt file that would tell you how wide each square is, and the domain and range.

**Comment by nJohnson02** [comment]
Finished a grid prototype, next to add not just square grids, and to add bottom and right lines.
